config/routes.rb
Chores::Application.routes.draw do
  resources :choretypes
  resources :contexts

 get '/about' => 'static_pages#about', as: :about_page
 get '/contact' => 'static_pages#contact', as: :contact_page

  resources :projects do
    collection do
      get :someday
      get :show_archived
      post :rebuild
    end
  end
  put 'project/:id/archive' => "projects#archive", as: 'archive_project'
  
  resources :chores do
    collection do
      get :occurrences
      get :status_quo
      get :calendar
      get :show_archived
    end
  end
  put 'chore/:id/skip' => "chores#skip", as: 'skip_chore'
  put 'chore/:id/archive' => "chores#archive", as: 'archive_chore'
  
  resources :emails do
  collection do
      get :login
      get :login_callback
      get :show_messages
      delete :delete_thread
      get :convert_to_project
    end
  end

  devise_for :users
  resources :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
  end

  root :to => 'static_pages#home'

end

app/models/project.rb
class Project < ActiveRecord::Base
  acts_as_nested_set :parent_column => :parent_project_id
  include TheSortableTree::Scopes
  
  attr_accessible :context_id, :parent_project_id, :title, :user_id, :comments, :someday, :thread_id, :email_address, :archived
  has_many :chores
  belongs_to  :context
  belongs_to :user

  belongs_to :parent, :class_name => "Project", :foreign_key => :parent_project_id
  has_many :children, :class_name => "Project", :foreign_key => :project_id

  validates(:title, presence: true)
  validates(:context_id, presence: true)
  validates(:user_id, presence: true)
  
 
  def thread_subject
      if(self.thread_id)
        email_account = Emailaccount.where(email_address: self.email_address).first
       inbox = Inbox::API.new(Rails.configuration.inbox_app_id, Rails.configuration.inbox_app_secret, email_account.authentication_token)
       thread = EmailsController.new.get_thread(inbox,self.thread_id)
       if thread
        thread.subject
      else
        "email not found"
      end
    end
    
  end
 
  def self.all_active_projects(context_id,user_id)
    if context_id == nil
      context_id = Context.first.id if Context.first
    end
   
    #temporary show all Projects from all contexts
    #@all_projects = Project.nested_set.select('*').where(:context_id => context_id, :user_id =>user_id, :someday => false)
    
    @all_projects = Project.nested_set.select('*').where(:user_id =>user_id, :someday => false, :archived => false)
    return @all_projects
  end

  def self.all_archived_projects(user_id)
    @all_projects = Project.where(:user_id =>user_id, :archived => true)
  end
  
  def self.empty_active_projects(context_id,user_id)
    if context_id == nil
      context_id = Context.first.id
    end
    #Project.nested_set.leaves.joins("LEFT OUTER JOIN chores on projects.id = chores.project_id").where({projects: {context_id: context_id,user_id: user_id, someday: false, archived: false}, chores: {id:nil}}).order("projects.lft asc")
    leaves_ids = Project.nested_set.leaves.where({context_id: context_id,user_id: user_id, someday: false, archived: false}).pluck(:id)
    non_empty_leaves_ids = Project.nested_set.leaves.joins("JOIN chores on projects.id = chores.project_id").where({projects: {context_id: context_id,user_id: user_id, someday: false, archived: false}, chores: {archived: false}}).pluck(:id)

    Project.find(leaves_ids - non_empty_leaves_ids)

  end
  
  def self.all_someday_projects(context_id,user_id)
    if context_id == nil
      context_id = Context.first.id
    end
   
    @all_projects = Project.nested_set.select('*').where(:context_id => context_id, :user_id =>user_id, :someday => true, :archived => false)
    return @all_projects
  end

  def parent_project_id=(parent_project_id)
    #if projects was put to someday list, it must be brought to root level
     #puts "launching setter"
    if(self.someday)
      #self.move_to_root
      write_attribute(:parent_project_id, nil)
      #puts "moving project with title="+self.title.to_s+" to root!"
    else
      write_attribute(:parent_project_id, parent_project_id)
    end
  end
  
  def context_id=(context_id)
    #if projects was children, they must all get the same id
    
    children_projects = self.descendants
    #puts "launching setter for project "+ self.id.to_s+", "+children_projects.length.to_s+" children found"
    
    children_projects.each do |project|
      project.update!(context_id: context_id)
     # puts "updating project "+project.id.to_s+" with context"+ context_id.to_s
    end
    write_attribute(:context_id, context_id)
    
  end

 # def delete
 #   children_projects = self.descendants
 #   children_projects.each do |project|
 #     project.update!(parent_project_id: self.parent_project_id)
 #   end
 #   Chore.where(:project_id => self.id).update_all(:project_id => nil)
 #   self.update!(:archived => true)
 #   #self.destroy
 # end
  
   def archive
    children_projects = self.descendants
    children_projects.each do |project|
      project.update!(parent_project_id: self.parent_project_id)
    end 
    Chore.where(:project_id => self.id).update_all(:project_id => nil)
    self.update_attribute(:archived, true)
    #self.archived = true
    #self.save
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  include TheSortableTreeController::Rebuild  
  include InboxConverter


before_filter :authenticate_user!
load_and_authorize_resource

 #stuff for sorted tree 
 # def manage
 #   @pages = Project.nested_set.select('project_id, title, context, parent_project_id').all
 # end

  # GET /projects
  # GET /projects.json
  def index
    #by default show only active projects, not someday projects
    @projects = Project.all_active_projects(params[:context],current_user.id )
    @chores = Chore.where("user_id = ?",current_user.id)
    @choretypes = Choretype.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end
  
  def someday
    #similar to main index, but show only someday projects
    @projects = Project.all_someday_projects(params[:context_id],current_user.id )
    @chores = Chore.where("user_id = ?",current_user.id)
    @choretypes = Choretype.all

    respond_to do |format|
      format.html # someday.html.erb
      format.json { render json: @projects }
    end
  end
  
   def show_archived
    @projects = Project.all_archived_projects(current_user.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chore }
    end
  end
  

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    #we need to unit test the email part
    if(@project.thread_id)
      email_account = Emailaccount.where(email_address: @project.email_address).first
      inbox = Inbox::API.new(Rails.configuration.inbox_app_id, Rails.configuration.inbox_app_secret, email_account.authentication_token)
      @messages = EmailsController.new.get_messages(inbox,@project.thread_id)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    session[:return_to] ||= request.referer
    @project = Project.new
    @project.user_id = current_user.id

    # we use list of projects and contexts on the view, need to prepare them
    @projects = Project.all_active_projects(params[:context_id],current_user.id )
    @contexts = Context.where("user_id = ?",current_user.id)


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    session[:return_to] ||= request.referer
     # we use list of projects and contexts on the view, need to prepare them
    @projects = Project.all_active_projects(params[:context_id],current_user.id )
    gon.projects = @projects
    @contexts = Context.where("user_id = ?",current_user.id)

    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
#    if(params[:project].parent_project_id = '')
    @project = Project.new(params[:project])
    @project.user_id = current_user.id

#if the project was created with a thread id, archive the thread
    if params[:project][:thread_id] then
      config = Rails.configuration
      #search for the email account is probably shitty here
      email_account = Emailaccount.where(email_address: params[:project][:email_address]).first
      inbox = Inbox::API.new(Rails.configuration.inbox_app_id, Rails.configuration.inbox_app_secret, email_account.authentication_token)
      EmailsController.new.archive_thread(inbox,params[:project][:thread_id])
    end

    respond_to do |format|
      if @project.save
        format.html { redirect_to session.delete(:return_to), notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    @project.user_id = current_user.id


    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to session.delete(:return_to), notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.delete

    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { head :no_content }
    end
  end
  
  # PUT archive/project/1
  # PUT archive/project/1.json
  def archive
    @project = Project.find(params[:id])
    @project.archive

    respond_to do |format|
      format.html { redirect_to request.referer}
      format.json { head :no_content }
    end
  end
  
  
 protected

  def sortable_model
    Project
  end

  def sortable_collection
    "projects"
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :context %><br />  
  <%= collection_select(:project, :context_id, @contexts, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :someday %><br />
    <%= f.check_box :someday %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
   <%= f.label :parent_project %><br />
   <%= collection_select(:project, :parent_project_id, @projects, :id, :title, {include_blank: 'None'}, {'data-behaviour' => 'parent_project_select'}) %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments, cols: 60, rows: 20 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing <%= @projects.length  if @projects != nil%> active projects</h1>

<%= link_to 'New Project', new_project_path,{:class => "btn btn-large btn-primary"}  %>

<% if @projects != nil and @projects.count != 0 %>

  <%= content_tag "ol", class: "sortable_tree",  data: {rebuild_url: rebuild_projects_url} do %>
    <%=  sortable_tree @projects, :locals => { :chores => @chores, :choretypes => @choretypes, :projects => @projects }  %>
  <% end%>

<% else %>
   <h2>No projects yet, create one!</h2>
<% end %>



<p><%=link_to 'Someday/May be projects',someday_projects_path %></p>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Context:</b>
  <%= @project.context.name %>
</p>

<p>
  <b>Title:</b>
  <%= @project.title %>
</p>

<p>
  <%if @project.someday %>
    Someday/May be
  <%else %>
   Active Project
  <%end %>
</p>

<p>
  <b>Parent project:</b>
  <%if @project.parent == nil %>
    -
  <%else %>
   <%= @project.parent.title %>
  <%end %>
</p>

<p>
  <b>Comments:</b>
  <%= @project.comments %>
</p>

<%if @project.thread_id != nil %>
<p>
  <b>Emails:</b>
  <table class="table">
  <tr>
    <th>Date</th>
    <th>From</th>
    <th>To</th>
    <th>Subject</th>
    <th>Body</th>
  </tr>

<% if @messages.count != 0%>

 <% @messages.each do |message| %>
  <tr>
    <td><%= Date.strptime(message.date.to_s, '%s') %></td>
    <td><%= message.from[0]['name'] %> <%= message.from[0]['email'] %></td>
    <td><%= message.to[0]['name'] %> <%= message.to[0]['email'] %></td>
    <td><%= message.subject %></td>
    <td><%=raw message.body %></td>
  </tr>
 <% end %>
<% end %>
</table>
</p>
<%end %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/show_archived.html.erb
<h1>Listing <%= @projects.length%> archived projects</h1>


 <table class="table">
   <tr>
     <th>Context</th>
     <th>Parent Project</th>
     <th>Title</th>
     <th>Some day</th>
     <th>email thread</th>
   </tr>

 <% if @projects.length >0%>
  <% @projects.each do |project| %>
   <tr>
     <td>
       <% if project.context_id != nil %>
        <%= project.context.name %>
       <% else %>
        -
       <%end%>
     </td>
     <td>
        <% if project.parent_project_id != nil %>
        <%= @projects.find(project.parent_project_id).title %>
       <% else %>
        -
       <%end%>
     </td>
    
     <td><%= link_to project.title, edit_project_path(project)%></td>
     
     <td>
       <% if project.someday %>
        yes
       <% else %>
        no
       <%end%>
     </td>
     <td>
       <% if project.thread_id != nil %>
         <%= project.thread_subject %>     
       <% else %>
        -
       <%end%>
     </td>

   </tr>
  <% end %>
 <% else %>
   <tr><td colspan=5>No projects archived yet</td><tr>
 <% end %>
 </table>

app/views/projects/someday.html.erb
<h1>Listing <%= @projects.length  if @projects != nil%> Someday/May be Projects</h1>

<% if @projects != nil and @projects.length > 0 %>

  <%= content_tag "ol", class: "sortable_tree",  data: {rebuild_url: rebuild_projects_url} do %>
    <%=  sortable_tree @projects, :locals => { :chores => @chores, :choretypes => @choretypes, :projects => @projects }%>
  <% end%>

<% else %>
   <h2>No projects there, all projects are active</h2>
<% end %>

<%= link_to 'New Project', new_project_path,{:class => "btn btn-large btn-primary"}  %>

<p><%=link_to 'Active projects',projects_path %></p>