config/routes.rb
Chores::Application.routes.draw do
  resources :choretypes
  resources :contexts

 get '/about' => 'static_pages#about', as: :about_page
 get '/contact' => 'static_pages#contact', as: :contact_page

  resources :projects do
    collection do
      get :someday
      get :show_archived
      post :rebuild
    end
  end
  put 'project/:id/archive' => "projects#archive", as: 'archive_project'
  
  resources :chores do
    collection do
      get :occurrences
      get :status_quo
      get :calendar
      get :show_archived
    end
  end
  put 'chore/:id/skip' => "chores#skip", as: 'skip_chore'
  put 'chore/:id/archive' => "chores#archive", as: 'archive_chore'
  
  resources :emails do
  collection do
      get :login
      get :login_callback
      get :show_messages
      delete :delete_thread
      get :convert_to_project
    end
  end

  devise_for :users
  resources :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
  end

  root :to => 'static_pages#home'

end

app/controllers/choretypes_controller.rb
class ChoretypesController < ApplicationController
  # GET /choretypes
  # GET /choretypes.json
  def index
    @choretypes = Choretype.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @choretypes }
    end
  end

  # GET /choretypes/1
  # GET /choretypes/1.json
  def show
    @choretype = Choretype.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @choretype }
    end
  end

  # GET /choretypes/new
  # GET /choretypes/new.json
  def new
    @choretype = Choretype.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @choretype }
    end
  end

  # GET /choretypes/1/edit
  def edit
    @choretype = Choretype.find(params[:id])
  end

  # POST /choretypes
  # POST /choretypes.json
  def create
    @choretype = Choretype.new(params[:choretype])

    respond_to do |format|
      if @choretype.save
        format.html { redirect_to @choretype, notice: 'Choretype was successfully created.' }
        format.json { render json: @choretype, status: :created, location: @choretype }
      else
        format.html { render action: "new" }
        format.json { render json: @choretype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /choretypes/1
  # PUT /choretypes/1.json
  def update
    @choretype = Choretype.find(params[:id])

    respond_to do |format|
      if @choretype.update_attributes(params[:choretype])
        format.html { redirect_to @choretype, notice: 'Choretype was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @choretype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choretypes/1
  # DELETE /choretypes/1.json
  def destroy
    @choretype = Choretype.find(params[:id])
    @choretype.destroy

    respond_to do |format|
      format.html { redirect_to choretypes_url }
      format.json { head :no_content }
    end
  end
end

app/views/choretypes/_form.html.erb
<%= form_for(@choretype) do |f| %>
  <% if @choretype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@choretype.errors.count, "error") %> prohibited this choretype from being saved:</h2>

      <ul>
      <% @choretype.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choretypes/edit.html.erb
<h1>Editing choretype</h1>

<%= render 'form' %>

<%= link_to 'Show', @choretype %> |
<%= link_to 'Back', choretypes_path %>

app/views/choretypes/index.html.erb
<h1>Listing choretypes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @choretypes.each do |choretype| %>
  <tr>
    <td><%= choretype.name %></td>
    <td><%= link_to 'Show', choretype %></td>
    <td><%= link_to 'Edit', edit_choretype_path(choretype) %></td>
    <td><%= link_to 'Destroy', choretype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Choretype', new_choretype_path %>

app/views/choretypes/new.html.erb
<h1>New choretype</h1>

<%= render 'form' %>

<%= link_to 'Back', choretypes_path %>

app/views/choretypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @choretype.name %>
</p>


<%= link_to 'Edit', edit_choretype_path(@choretype) %> |
<%= link_to 'Back', choretypes_path %>