config/routes.rb
Chores::Application.routes.draw do
  resources :choretypes
  resources :contexts

 get '/about' => 'static_pages#about', as: :about_page
 get '/contact' => 'static_pages#contact', as: :contact_page

  resources :projects do
    collection do
      get :someday
      get :show_archived
      post :rebuild
    end
  end
  put 'project/:id/archive' => "projects#archive", as: 'archive_project'
  
  resources :chores do
    collection do
      get :occurrences
      get :status_quo
      get :calendar
      get :show_archived
    end
  end
  put 'chore/:id/skip' => "chores#skip", as: 'skip_chore'
  put 'chore/:id/archive' => "chores#archive", as: 'archive_chore'
  
  resources :emails do
  collection do
      get :login
      get :login_callback
      get :show_messages
      delete :delete_thread
      get :convert_to_project
    end
  end

  devise_for :users
  resources :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
  end

  root :to => 'static_pages#home'

end

app/models/choretype.rb
class Choretype < ActiveRecord::Base

  attr_accessible :name
  has_many :chores
  
  validates( :name, presence: true)
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
include IceCube
before_filter :authenticate_user!
#load_and_authorize_resource 


  # GET /chores
  # GET /chores.json
  def index
    @contexts = Context.where("user_id = ?",current_user.id)
    @choretypes = Choretype.all


    if @contexts.empty?
      @active_context = nil
      @chores = nil
    else
      if params[:context] == nil
        @active_context = @contexts.first.id
      else
        @active_context = params[:context].to_s
      end
     
      if params[:choretype] == nil
        @active_choretype = @choretypes.first.id
      else
        @active_choretype = params[:choretype].to_s
      end

      @chores = Chore.all_chores_by_context_type_and_user(@active_context,@active_choretype, current_user.id)
      #also prepare active projects, because we use it to display project titles.
      #puts "chores controller calling projects with context "+@active_context.to_s+" and user_id "+current_user.id.to_s
      @projects = Project.all_active_projects(@active_context,current_user.id )
    end
    
        respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chores }
    end
  end
  
   # GET /calendar
  # GET /calendar.json
  def calendar
    #we don't prepare any data, all info is requested by the calendar dynamically    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calendar }
    end
  end
  
  # GET /status_quo
  # GET /status_quo.json
  def status_quo
    @contexts = Context.where("user_id = ?",current_user.id)
    @choretypes = Choretype.all
    if @contexts.empty?
      @active_context = nil
    else
      if params[:context] == nil
        @active_context = @contexts.first.id
      else
        @active_context = params[:context].to_s
      end
     
      choretype_todo = 1 #Warning: using undeclared constants!
      choretype_waiting = 2
      choretype_appointment = 3
            
      @chores = Chore.all_active_chores(@active_context,choretype_todo, current_user.id)
      @waiting_chores = Chore.all_active_chores(@active_context,choretype_waiting, current_user.id)
    
      @appointments = Chore.all_today_and_missed_appointments(@active_context,choretype_appointment, current_user.id)
      @projects = Project.all_active_projects(@active_context,current_user.id )
      @empty_projects = Project.empty_active_projects(@active_context,current_user.id )
      @orphan_chores = Chore.orphan_chores
    end
    
        respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chores }
    end
  end
  
  # GET /occurrences.json only!
  def occurrences
    @contexts = Context.where("user_id = ?",current_user.id)


    if @contexts.empty?
      @active_context = nil
      @occurrences = nil
    else
      if params[:context] == nil
        @active_context = @contexts.first.id
      else
        @active_context = params[:context].to_s
      end
     
    #puts "got params  "+params.to_s
    
    begin
         start_date = Date.parse(params[:start])
      rescue ArgumentError
         return nil
    end
    begin
         end_date = Date.parse(params[:end])
      rescue ArgumentError
         return nil
    end
      
      @occurrences = Chore.appointment_occurrences(@active_context,start_date,end_date, current_user.id)
    end
    
    #occurrences need to be formated in json with options http://fullcalendar.io/docs/event_data/Event_Object/
    
    respond_to do |format|
      format.json { render json: @occurrences }
    end
  end
  

  # GET /chores/1
  # GET /chores/1.json
  def show
    
    @chore = Chore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chore }
    end
  end
  
   def show_archived
      @chores = Chore.all_archived_chores(current_user.id)
      @projects = Project.all_active_projects(@active_context,current_user.id )
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chore }
    end
  end

  # GET /chores/new
  # GET /chores/new.json
  def new
    session[:return_to] ||= request.referer 
    @chore = Chore.new
    @chore.user_id = current_user.id

    # we use list of projects and emails on the view, need to prepare them
   
   @projects = Project.all_active_projects(params[:context],current_user.id )
   @emails = Email.where("user_id = ?",current_user.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chore }
    end
  end

  # GET /chores/1/edit
  def edit
    session[:return_to] ||= request.referer 
    #@projects = Project.where({user_id: current_user.id, someday: false})
    @projects = Project.all_active_projects(params[:context_id],current_user.id )
    @emails = Email.where("user_id = ?",current_user.id)
    @chore = Chore.find(params[:id])
  end

  # POST /chores
  # POST /chores.json
  def create
    if(params[:chore][:choretype_id] == '1' or params[:chore][:choretype_id] == '2')
        params[:chore][:startdate] = ''
        params[:chore][:starttime] = ''
        params[:chore][:endtime] = ''
        params[:chore][:deadline] = ''
        params[:chore][:all_day] = '1'
      else
        #if schedule is present - update startdate and deadline to the first occurrence
        if(params[:chore][:schedule] != '' and params[:chore][:schedule] != nil and params[:chore][:schedule] != 'null')
          schedule = IceCube::Schedule.new(Time.zone.now)
          schedule.add_recurrence_rule(RecurringSelect.dirty_hash_to_rule(params[:chore][:schedule]))
          params[:chore][:startdate]=schedule.first.strftime("%m/%d/%Y")
          params[:chore][:deadline]=schedule.first.strftime("%m/%d/%Y")
          #puts "New date is "+params[:chore][:deadline]
        end
        #form correct deadline parameter
        if(params[:chore][:deadline] != '' and params[:chore][:deadline] != nil and params[:chore][:deadline] != "not set")
          end_datetime = DateTime.strptime(params[:chore][:deadline], "%m/%d/%Y")
          end_datetime=end_datetime.change(offset:"-0500")
          if(params[:chore][:all_day] == '0')
            end_datetime=end_datetime.change(hour: params[:end_time]["time(4i)"].to_i, min: params[:end_time]["time(5i)"].to_i )
          end
          params[:chore][:deadline]=  end_datetime.strftime("%Y-%m-%d %H:%M %z")
        end
         #form correct startdate parameter
        if(params[:chore][:startdate] != '' and params[:chore][:startdate] != nil and params[:chore][:startdate] != "not set")
          start_datetime = DateTime.strptime(params[:chore][:startdate], "%m/%d/%Y")
          start_datetime=start_datetime.change(offset:"-0500")
          if(params[:chore][:all_day] == '0')
            start_datetime=start_datetime.change(hour: params[:start_time]["time(4i)"].to_i, min: params[:start_time]["time(5i)"].to_i )
          end
          params[:chore][:startdate]=  start_datetime.strftime("%Y-%m-%d %H:%M %z")
        end
      end

   # print "create chores controller launched with ", params,"\n"

    @chore = Chore.new(params[:chore])
    @chore.user_id = current_user.id

    #attempt to serialize schedule correctly
    #@chore.schedule = IceCube::Schedule.from_yaml(params[:chore][:schedule])
    
    respond_to do |format|
      if @chore.save
        format.html { redirect_to session.delete(:return_to), notice: 'Chore was successfully created.' }
        format.json { render json: @chore, status: :created, location: @chore }
      else
        format.html { render action: "new" }
        format.json { render json: @chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chores/1
  # PUT /chores/1.json
  def update
    @chore = Chore.find(params[:id])
    @chore.user_id = current_user.id

  #  print "chore update controller received params: ", params,"\n"
    
    
    respond_to do |format|
      
      if(params[:chore][:choretype_id] == '1' or params[:chore][:choretype_id] == '2')
        params[:chore][:startdate] = ''
        params[:chore][:starttime] = ''
        params[:chore][:endtime] = ''
        params[:chore][:deadline] = ''
        params[:chore][:all_day] = '1'
      else
        #if schedule is present - update startdate and deadline to the first occurrence
        if(params[:chore][:schedule] != '' and params[:chore][:schedule] != nil and params[:chore][:schedule] != 'null')
          schedule = IceCube::Schedule.new(Time.zone.now)
          schedule.add_recurrence_rule(RecurringSelect.dirty_hash_to_rule(params[:chore][:schedule]))
          params[:chore][:startdate]=schedule.first.strftime("%m/%d/%Y")
          params[:chore][:deadline]=schedule.first.strftime("%m/%d/%Y")
        end	 
        #form correct deadline parameter
        if(params[:chore][:deadline] != '' and params[:chore][:deadline] != nil and params[:chore][:deadline] != "not set")
          end_datetime = DateTime.strptime(params[:chore][:deadline], "%m/%d/%Y")
          end_datetime=end_datetime.change(offset:"-0500")
          if(params[:chore][:all_day] == '0')
            end_datetime=end_datetime.change(hour: params[:end_time]["time(4i)"].to_i, min: params[:end_time]["time(5i)"].to_i )
          end  
          params[:chore][:deadline]=  end_datetime.strftime("%Y-%m-%d %H:%M %z")
        end
	 #form correct startdate parameter
        if(params[:chore][:startdate] != '' and params[:chore][:startdate] != nil and params[:chore][:startdate] != "not set")
          start_datetime = DateTime.strptime(params[:chore][:startdate], "%m/%d/%Y")
          start_datetime=start_datetime.change(offset:"-0500")
          if(params[:chore][:all_day] == '0')
            start_datetime=start_datetime.change(hour: params[:start_time]["time(4i)"].to_i, min: params[:start_time]["time(5i)"].to_i )
          end  
          params[:chore][:startdate]=  start_datetime.strftime("%Y-%m-%d %H:%M %z")
        end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :size => "90" %>
  </div>
 <div class="field">
    <%= f.label :project %><br />
    <%= select_tag :project_id, nested_options(@projects, :selected => @chore.project), class: :nested_options, name: "chore[project_id]", id: "chore[project_id]" %>
  </div>
 <div class="field">
    <%= f.label :next_action %><br />
    <%= f.check_box :next_action %>
  </div>
  <div class="field">
    <%= f.label :choretype %><br />
    <%= collection_select(:chore, :choretype_id, Choretype.all, :id, :name, {}, {'data-behaviour' => 'choretype_select'})%>
  </div>
  
<div class="panel panel-primary" id="first_appointment_panel">
 <div class="panel-heading">First appointment</div>
 <div class="panel-body">
    
  <div class="field" >
    <%= f.label :startdate %><br />
    <% if @chore.startdate != nil %>
     <input type="text" data-behaviour='datepicker'  value="<%=@chore.startdate.to_s(:due_date)%>" name="chore[startdate]" id="chore_startdate">
    <% else %>
      <input type="text" data-behaviour='datepicker'  value="not set"  name="chore[startdate]" id="chore_startdate">
    <%end%>
  </div>
     
  <div class="field" >
    <%= f.label :deadline %><br />
    <% if @chore.deadline != nil %>
     <input type="text" data-behaviour='datepicker'  value="<%=@chore.deadline.to_s(:due_date)%>" name="chore[deadline]" id="chore_deadline">
    <% else %>
      <input type="text" data-behaviour='datepicker'  value="not set"  name="chore[deadline]" id="chore_deadline">
    <%end%>
  </div>
 
  <div class="field">
    <%= f.label :all_day %><br />
    <%= f.check_box :all_day, data: {'behaviour' => 'all_day_checkbox'} %>
  </div>
     
  <div class="field" id="start_time">
    Start time<br />
   
    <% if @chore.startdate != nil %>
     
     <%= time_select "start_time", "time", {:ampm=> true,:selected => Time.parse(@chore.startdate.to_s), :minute_step => 15} %>
    <% else %>
      <%= time_select "start_time", "time",{:ampm=> true, :minute_step => 15} %>
    <%end%>
  </div> 
     
  <div class="field" id="end_time">
    End time<br />
    <% if @chore.deadline != nil %>
     <%= time_select "end_time", "time",{:ampm=> true, :selected => Time.parse(@chore.deadline.to_s), :minute_step => 15} %>
    <% else %>
     <%= time_select "end_time", "time",{:ampm=> true, :minute_step => 15} %>
    <%end%>
  </div>     
 
 </div>
</div>


<div class="panel panel-primary" id="frequency_panel">
 <div class="panel-heading">Frequency:</div>
 <div class="panel-body">
 
 <%= f.select_recurring :schedule, nil, :allow_blank => true %>
  
 </div>
</div>

  <div class="field">
    <%= f.label :email %><br />
    <%= collection_select(:chore, :email_id, @emails, :id, :subject, {include_blank: 'None'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/chores/calendar.html.erb
<h1>Calendar</h1>
<%= link_to 'New Chore', new_chore_path, {:class => "btn btn-large btn-primary"} %>
<div id='calendar'></div>


 

app/views/chores/edit.html.erb
<h1>Editing chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<h1>Listing <%= @chores.length%> active chores</h1>

 <ul class="nav nav-tabs">
<% if @contexts.length == 0 %>
No contexts yet, create one!
<% else %>
 <% @contexts.each do |context| %>
    <% if context.id.to_s == @active_context.to_s%>
     <li class="active"><%=link_to context.name, chores_path(:context => context.id, :choretype => @active_choretype.to_s) %></li>
    <% else %>
     <li><%=link_to context.name, chores_path(:context => context.id, :choretype => @active_choretype.to_s) %></li>
    <% end %>
 <% end %>
  </ul>

 <ul class="nav nav-pills">

 <% @choretypes.each do |choretype| %>
    <% if choretype.id.to_s == @active_choretype.to_s%>
     <li class="active"><%=link_to choretype.name, chores_path(:context => @active_context, :choretype => choretype) %></li>
    <% else %>
     <li><%=link_to choretype.name, chores_path(:context => @active_context, :choretype => choretype) %></li>
    <% end %>
 <% end %>
  <li><%=link_to 'Projects',projects_path(:context => @active_context) %></li>
 </ul>
 <% if (@active_choretype.to_s == '3') %>
 <div id='calendar'></div>
 <% end %>
 
 <table class="table">
   <tr>
     <th>Project</th>
     <th>Title</th>
     <th>Email</th>
     <th>Start Date</th>
     <th>Deadline</th>
     <th>Schedule</th>
     <th></th>
   </tr>

 <% if @chores.length >0%>
  <% @chores.each do |chore| %>
   <tr>
     <td>
        <%project_id_iterator = chore.project_id%>
        <%project_path = ''%>
        <%while project_id_iterator != nil%>
          <%project_path =  link_to(@projects.find(project_id_iterator).title, edit_project_path(@projects.find(project_id_iterator))) +' > '+ project_path%>
          <% project_id_iterator = @projects.find(project_id_iterator).parent_project_id %>
        <%end%>
        <%=project_path%>
     </td>
     <td><%= link_to chore.title, edit_chore_path(chore)%></td>
     <td>
       <%if chore.email == nil %>
        -
       <%else %>
        <%= chore.email.subject %>
       <%end %>
     </td>
     <td>
       <% if chore.startdate != nil %>
        <%= chore.startdate.to_s(:due_date) %>
       <% else %>
        -
       <%end%>
     </td>
     <td>
       <% if chore.deadline != nil %>
        <%= chore.deadline.to_s(:due_date) %>
       <% else %>
        -
       <%end%>
     </td>
     <td>
      <% if(chore.schedule != {} and chore.schedule != nil)%>
       <%= RecurringSelect.dirty_hash_to_rule(chore.schedule).to_s%>
      <% else %>
       -
      <%end%>  
     </td>
     
     <td><%= link_to "Delete", chore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
   </tr>
  <% end %>
 <% else %>
   <tr><td colspan=9>No chores yet, create one!</td><tr>
 <% end %>
 </table>

 <br />

 <%= link_to 'New Chore', new_chore_path, {:class => "btn btn-large btn-primary"} %>
 

<% end %>

app/views/chores/new.html.erb
<h1>New chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
     <%if @chore.email_id == nil %>
      -
    <%else %>
     <%= @chore.email.subject %>
    <%end %>
</p>

<p>
  <b>Title:</b>
  <%= @chore.title %>
</p>

<p>
  <b>Start Date:</b>
  <% if @chore.startdate != nil %>
   <%= @chore.startdate.strftime("%m/%d/%Y at %I:%M%p") %>
  <% else %>
    -
  <%end%>
</p>

<p>
  <b>Deadline:</b>
  <% if @chore.deadline != nil %>
   <%= @chore.deadline.strftime("%m/%d/%Y at %I:%M%p")  %>
  <% else %>
    -
  <%end%>
</p>

<p>
  <b>Type:</b>
  <%= @chore.choretype.name %>
</p>

<p>
  <b>Project:</b>
  <%= @chore.project.title %>
</p>

<p>
  <b>Schedule:</b>
   <% if(@chore.schedule!= {} and @chore.schedule != nil)%>
    <%=IceCube::Schedule.from_hash(@chore.schedule).to_s %>
   <% else %>
    not recurring
  <%end%>
</p>



<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>

app/views/chores/show_archived.html.erb
<h1>Listing <%= @chores.length%> active chores</h1>


 <table class="table">
   <tr>
     <th>Context</th>
     <th>Project</th>
     <th>Type</th>
     <th>Title</th>
     <th>Start Date</th>
     <th>Deadline</th>
     <th>Schedule</th>
   </tr>

 <% if @chores.length >0%>
  <% @chores.each do |chore| %>
   <tr>
     <td>
       <% if chore.project_id != nil %>
        <%= chore.project.context.name %>
       <% else %>
        -
       <%end%>
     </td>
     <td>
        <%project_id_iterator = chore.project_id%>
        <%project_path = ''%>
        <%while project_id_iterator != nil%>
          <%project_path =  link_to(@projects.find(project_id_iterator).title, edit_project_path(@projects.find(project_id_iterator))) +' > '+ project_path%>
          <% project_id_iterator = @projects.find(project_id_iterator).parent_project_id %>
        <%end%>
        <%=project_path%>
     </td>
     
      <td>
       <% if chore.choretype_id != nil %>
        <%= chore.choretype.name %>
       <% else %>
        -
       <%end%>
     </td>
     
     <td><%= link_to chore.title, edit_chore_path(chore)%></td>
     
     <td>
       <% if chore.startdate != nil %>
        <%= chore.startdate.to_s(:due_date) %>
       <% else %>
        -
       <%end%>
     </td>
     <td>
       <% if chore.deadline != nil %>
        <%= chore.deadline.to_s(:due_date) %>
       <% else %>
        -
       <%end%>
     </td>
     <td>
      <% if(chore.schedule != {} and chore.schedule != nil)%>
       <%= RecurringSelect.dirty_hash_to_rule(chore.schedule).to_s%>
      <% else %>
       -
      <%end%>  
     </td>
    
   </tr>
  <% end %>
 <% else %>
   <tr><td colspan=9>No chores archived yet</td><tr>
 <% end %>
 </table>

app/views/chores/status_quo.erb
<h1>Status Quo <%=Time.zone.now.to_date%></h1>
<p><%= link_to 'New Chore', new_chore_path, {:class => "btn btn-large btn-primary"} %> </p>

<div class="col-lg-8">
 <ul class="nav nav-tabs">
     
<% if @contexts.length == 0 %>
No contexts yet, create one!
<% else %>
 <% @contexts.each do |context| %>
    <% if context.id.to_s == @active_context.to_s%>
     <li class="active"><%=link_to context.name, status_quo_chores_path(:context => context.id) %></li>
    <% else %>
     <li><%=link_to context.name, status_quo_chores_path(:context => context.id) %></li>
    <% end %>
 <% end %>
  </ul>
<% if @appointments.length > 0%>
<h2><%= @appointments.length%> appointments</h2>

<table class="table-condensed">
   <tr>
     <th>Project</th>
     <th>Title</th>
     <th>Email</th>
     <th>Start Date</th>
     <th>Deadline</th>
     <th>Schedule</th>
     <th></th>
     <th></th>
   </tr>


  <% @appointments.each do |chore| %>
   <tr>
     <td>
        <%project_id_iterator = chore.project_id%>
        <%project_path = ''%>
        <%while project_id_iterator != nil%>
          <%project_path =  link_to(@projects.find(project_id_iterator).title, edit_project_path(@projects.find(project_id_iterator))) +' > '+ project_path%>
          <% project_id_iterator = @projects.find(project_id_iterator).parent_project_id %>
        <%end%>
        <%=project_path%>
     </td>
     <td><%= link_to chore.title, edit_chore_path(chore)%></td>
     <td>
       <%if chore.email == nil %>
        -
       <%else %>
        <%= chore.email.subject %>
       <%end %>
     </td>
     <td>
       <% if chore.startdate != nil %>
        <%= chore.startdate.to_s(:due_date) %>
       <% else %>
        -
       <%end%>
     </td>
     <td>
       <% if chore.deadline != nil %>
        <%= chore.deadline.to_s(:due_date) %>
       <% else %>
        -
       <%end%>
     </td>
     <td>
      <% if(chore.schedule != {} and chore.schedule != nil)%>
       <%= RecurringSelect.dirty_hash_to_rule(chore.schedule).to_s%>
      <% else %>
       -
      <%end%>  
     </td>
     <td>
       <% if(chore.schedule != {} and chore.schedule != nil)%>
        <%= link_to "Skip", skip_chore_path(chore), method: :put %>
       <% else %>
        -
       <%end%>
     </td>
     <td class="text-right"><%= link_to "Archive", archive_chore_path(chore), method: :put, data: { confirm: 'Are you sure?' } %></td>
   </tr>
  
  <% end %>
 </table>
 <% end %>

<% if @chores.length > 0%>

<h2><%= @chores.length%> Chores</h2>

<table class="table-condensed">
   <tr>
     <th>Project</th>
     <th>Title</th>
     <th>Email</th>
     <th></th>
   </tr>

  <% @chores.each do |chore| %>
   <tr>
     <td>
        <%project_id_iterator = chore.project_id%>
        <%project_path = ''%>
        <%while project_id_iterator != nil%>
          <%project_path =  link_to(@projects.find(project_id_iterator).title, edit_project_path(@projects.find(project_id_iterator))) +' > '+ project_path%>
          <% project_id_iterator = @projects.find(project_id_iterator).parent_project_id %>
        <%end%>
        <%=project_path%>
     </td>
     <td><%= link_to chore.title, edit_chore_path(chore)%></td>
     <td>
       <%if chore.email == nil %>
        -
       <%else %>
        <%= chore.email.subject %>
       <%end %>
     </td>
     <td class="text-right"><%= link_to "Archive", archive_chore_path(chore), method: :put, data: { confirm: 'Are you sure?' } %></td>
   </tr>
  <% end %>
 </table>
<% end %>

<% if @orphan_chores.length >0 %>

<h2><%= @orphan_chores.length%> Orphan Chores</h2>

<table class="table-condensed">
   <tr>
     <th>Title</th>
     <th>Email</th>
     <th></th>
   </tr>

  <% @orphan_chores.each do |chore| %>
   <tr>
     <td><%= link_to chore.title, edit_chore_path(chore)%></td>
     <td>
       <%if chore.email == nil %>
        -
       <%else %>
        <%= chore.email.subject %>
       <%end %>
     </td>
     <td class="text-right"><%= link_to "Archive", archive_chore_path(chore), method: :put, data: { confirm: 'Are you sure?' } %></td>
   </tr>
  <% end %>
 </table>
<% end %>


 <% if @waiting_chores.length > 0 %>
<h2>Waiting for <%= @waiting_chores.length%> chores</h2>

<table class="table-condensed">
   <tr>
     <th>Project</th>
     <th>Title</th>
     <th>Email</th>
     <th></th>
   </tr>


  <% @waiting_chores.each do |chore| %>
   <tr>
     <td>
        <%project_id_iterator = chore.project_id%>
        <%project_path = ''%>
        <%while project_id_iterator != nil%>
          <%project_path =  link_to(@projects.find(project_id_iterator).title, edit_project_path(@projects.find(project_id_iterator))) +' > '+ project_path%>
          <% project_id_iterator = @projects.find(project_id_iterator).parent_project_id %>
        <%end%>
        <%=project_path%>
     </td>
     <td><%= link_to chore.title, edit_chore_path(chore)%></td>
     <td>
       <%if chore.email == nil %>
        -
       <%else %>
        <%= chore.email.subject %>
       <%end %>
     </td>
     <td class="text-right"><%= link_to "Archive", archive_chore_path(chore), method: :put, data: { confirm: 'Are you sure?' } %></td>
   </tr>
   <%  end %>
 </table>
<%  end %>


 
  <% if @empty_projects.length >0 %>
<h2>Listing <%= @empty_projects.length  if @empty_projects != nil%> empty projects</h2>

<table class="table-condensed">
   <tr>
     <th>Title</th>
     <th></th>
   </tr>


  <% @empty_projects.each do |project| %>
   <tr>
     <td>
        <%project_id_iterator = project.id%> 
        <%project_path = ''%> 
        <%while project_id_iterator != nil%> 
          <%project_path =  link_to(Project.find(project_id_iterator).title, edit_project_path(Project.find(project_id_iterator))) +' > '+ project_path%> 
          <% project_id_iterator = Project.find(project_id_iterator).parent_project_id %> 
        <%end%>
        <%=project_path%> 
     </td>
         
     <td class="text-right"><%= link_to "Archive", archive_project_path(project), method: :put, data: { confirm: 'Are you sure?' } %></td>
   </tr>

    <% end %>
 </table>
 <% end %>

<% end %>

</div>

<div class="col-lg-4">

<div id="daily_calendar_container">
 <div id='daily_calendar'></div>
</div>

</div>