config/routes.rb
Chores::Application.routes.draw do
  resources :choretypes
  resources :contexts

 get '/about' => 'static_pages#about', as: :about_page
 get '/contact' => 'static_pages#contact', as: :contact_page

  resources :projects do
    collection do
      get :someday
      get :show_archived
      post :rebuild
    end
  end
  put 'project/:id/archive' => "projects#archive", as: 'archive_project'
  
  resources :chores do
    collection do
      get :occurrences
      get :status_quo
      get :calendar
      get :show_archived
    end
  end
  put 'chore/:id/skip' => "chores#skip", as: 'skip_chore'
  put 'chore/:id/archive' => "chores#archive", as: 'archive_chore'
  
  resources :emails do
  collection do
      get :login
      get :login_callback
      get :show_messages
      delete :delete_thread
      get :convert_to_project
    end
  end

  devise_for :users
  resources :users

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
  end

  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="container">
<% [:notice, :error, :alert, :success].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="<%= flash_class(level) %>">
      <%= content_tag :span, flash[level] %>
    </div>
  <% end %>
<% end %>
</div>
<div class="container">
  <small>
    <a href="http://chores.com/">Chores</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", :about_page   %></li>
      <li><%= link_to "Contact", :contact_page %></li>
      <li><a href="http://news.chores.com/">News</a></li>
    </ul>
  </nav>

</div>
</footer>

app/views/layouts/_header.html.erb
    <header>
    

    <nav class="navbar navbar-fixed-top navbar-inverse ">
       <div class="container">

      <div class="navbar-left">
          <% if user_signed_in? %>
          <%= link_to "Home", '/', id: "logo" %>
          <%= link_to "Emails", emails_path, id: "logo" %> 
          <%if current_user.unread_inbox_emails %>
            <%= image_tag("unread_email.png", :alt => "unread emails", :class => "style_email_flag") %>
          <% else %>
            <%if current_user.total_inbox_emails %>
              <%= image_tag("read_email.png", :alt => "unread emails", :class => "style_email_flag") %>
            <% end %>
          <% end %>
          <%= link_to "Status Quo", status_quo_chores_path, id: "logo" %>
          <%= link_to "Calendar", calendar_chores_path, id: "logo" %>
          <%= link_to "Projects", projects_path, id: "logo" %>
          <%if current_user.unread_project_emails %>
            <%= image_tag("unread_email.png", :alt => "unread emails", :class => "style_email_flag") %>
          <% end %>
          <%= link_to "Contexts", contexts_path, id: "logo" %>
          <% else %>
          <%= link_to "Chores", '/', id: "logo" %>
          <% end %>
       </div>

      <div class="navbar-right navbar-inverse">
       <p class="navbar-text">
          <% if user_signed_in? %>
              Signed in as: <%= current_user.email %>

 	  <%= link_to('Log Out', destroy_user_session_path, data: {:method => :delete, :confirm => 'Are you sure?'}, :class => 'navbar-link')%>

          <% else %>
              <%= link_to('Log In', new_user_session_path, {:class => "navbar-link"}) %>
          <% end %>
        </p>
      </nav>
      </div>
    </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Rails.env %> Chores - <%= yield(:subtitle) %></title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div id="wrap">
    <div class="container-fluid">
      <%= yield %>
    </div>
<div id="push"></div>
</div>
<div style = "margin-bottom: 50px;"></div>
<%= render 'layouts/footer' %>
</body>
</html>